# Generated by Django 6.0.7 on 2026-08-30 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers are displayed first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='events.event')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'created_at'],
                'indexes': [models.Index(fields=['event', 'is_active'], name='faq_faq_event_i_fe225a_idx'), models.Index(fields=['event', 'display_order'], name='faq_faq_event_i_208308_idx')],
            },
        ),
    ]
