# Generated by Django 5.2.17 on 2026-09-18 04:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('zone', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('SIMULATION', 'Simulation (demo)'), ('LIVE', 'Live (Hikvision ISAPI/RTSP)')], default='SIMULATION', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.PositiveIntegerField(default=80)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=200)),
                ('rtsp_url', models.URLField(blank=True, help_text='rtsp://user:pass@ip:554/Streaming/...')),
                ('channel', models.PositiveIntegerField(default=1, help_text='Hikvision kanal raqami')),
                ('substream', models.PositiveIntegerField(default=1, help_text='1 = asosiy, 2 = sub-stream')),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['zone', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('booth_number', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, help_text='Hudud / zal nomi', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, help_text='Stend egasi (ORGANIZER)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booths', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booth_number'],
            },
        ),
        migrations.CreateModel(
            name='ExpoVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('purpose', models.CharField(choices=[('BUSINESS', 'Business'), ('PARTNERSHIP', 'Partnership'), ('INVESTOR', 'Investor'), ('MEDIA', 'Media'), ('STUDENT', 'Student'), ('OTHER', 'Other')], default='BUSINESS', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='expo/visitors/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (inside)'), ('LEFT', 'Left')], default='ACTIVE', max_length=20)),
                ('check_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('badge_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sim_seed', models.IntegerField(default=0, editable=False)),
                ('planned_path', models.JSONField(blank=True, default=list, editable=False)),
                ('current_zone', models.CharField(blank=True, max_length=150)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expo_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=150)),
                ('kind', models.CharField(choices=[('REGISTERED', 'Registered'), ('SEEN', 'Seen by camera'), ('ENTERED', 'Entered zone'), ('EXITED', 'Exited zone'), ('LEFT', 'Left expo')], default='SEEN', max_length=20)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('booth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to='expo.booth')),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracking_events', to='expo.camera')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='expo.expovisitor')),
            ],
            options={
                'ordering': ['detected_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('SUCCESS', 'Success'), ('WARNING', 'Warning')], default='INFO', max_length=20)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='expo.expovisitor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expovisitor',
            index=models.Index(fields=['status', 'check_in_at'], name='expo_expovi_status_712665_idx'),
        ),
        migrations.AddIndex(
            model_name='expovisitor',
            index=models.Index(fields=['last_name', 'first_name'], name='expo_expovi_last_na_4c23ea_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['visitor', 'detected_at'], name='expo_tracki_visitor_5bdb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['booth', 'kind'], name='expo_tracki_booth_i_a57468_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['camera', 'detected_at'], name='expo_tracki_camera__6f4d0d_idx'),
        ),
    ]
