# Generated by Django 5.2.17 on 2026-09-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expovisitor',
            name='face_hash',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
