# Generated by Django 5.2.17 on 2026-09-18 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0002_expovisitor_face_hash'),
        ('registrations', '0004_alter_registration_checked_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expovisitor',
            name='offline_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expovisitor',
            name='registration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expo_visitor', to='registrations.registration'),
        ),
        migrations.AddField(
            model_name='expovisitor',
            name='source',
            field=models.CharField(choices=[('KIOSK', 'Kiosk terminal'), ('GATE_QR', 'Darvoza — QR ticket'), ('GATE_WALKIN', "Darvoza — joyida ro'yxat"), ('OFFLINE', 'Offline navbat (sinxronlandi)')], default='KIOSK', max_length=20),
        ),
        migrations.AddField(
            model_name='expovisitor',
            name='visit_type',
            field=models.CharField(choices=[('VISITOR', 'Mehmon (Guest)'), ('EXHIBITOR', 'Eksponent (Exhibitor)')], default='VISITOR', max_length=20),
        ),
    ]
