# Generated by Django 5.2.17 on 2026-09-18 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('ORGANIZER', 'Organizer'), ('ATTENDEE', 'Attendee'), ('SECURITY', 'Security (Xavfsizlik)')], default='ATTENDEE', max_length=20),
        ),
    ]
