# Generated by Django 6.0.7 on 2026-08-29 04:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('EVENT_CREATED', 'Event Created'), ('EVENT_UPDATED', 'Event Updated'), ('EVENT_REGISTERED', 'Event Registered'), ('EVENT_CANCELLED', 'Event Cancelled'), ('GENERAL', 'General')], default='GENERAL', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['-created_at'], name='notificatio_created_ae6ed6_idx'),
        ),
    ]
